# Use for running a single service for local dev
version: "3.9"  

services:
  base: &base
    build: .

  test: 
    <<: *base
    command: "test"

  run:
    <<: *base
    container_name: logger
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health_check"]
      interval: 5s
      timeout: 30s
      retries: 5
    user: user
    command: "serve"
    env_file: .env
    ports:
      - 8081:8080
    networks:
      - llm-tools
  
  bd:
    <<: *base
    container_name: dataset-builder
    user: user
    env_file: .env
    networks:
      - llm-tools

networks:
  llm-tools: 
    external: true
